### ISSUE TITLE
Add max thread count

### ISSUE THREAD

**Issue by lesleyxyz** [CyberKnight00/Argon2_Cracker#3]
I really appreciate this repo as john or hashcat do not have support for Argon, even after all these years.

Although when trying to crack a hash with rockyou.txt and 12gb RAM, the process gets killed because of the lack of RAM (even though I had all available before starting the program).

I think this is because a new thread keep being made for each line in the wordlist.
Having the ability to specify a max thread count should help this.

Just a suggestions, maybe I'll even try and implement it

**Comment by CyberKnight00** [comment]
Hi @lesleyxyz,
Thank you for the suggestion. I have added the feature to specify a max thread count.
Command to specify number of threads to use as follows 

crack_argon2.py -t <THREADS> -c <ARGON2_HASH> -w <WORDLIST>
or
crack_argon2.py --threads=THREADS --crack=ARGON2_HASH --wordlist=WORDLIST
