### ISSUE TITLE
No matching distribution found for concurrent-futures

### ISSUE THREAD

**Issue by Jamolo5** [CyberKnight00/Argon2_Cracker#4]
Current when trying to install requirements;
`pip 3 install -r requirement.txt`

Results in the following error message:
"No matching distribution found for concurrent-futures"

**Comment by CyberKnight00** [comment]
Hi @Jamolo5,

Thank you for bringing this to my attention. I have updated the requirement.txt. The only requirements are argon2-cffi and termcolor.

concurrent.futures is included in the standard library of Python 3. Therefore no need to install any module.

**Comment by CyberKnight00** [comment]
Please use the latest updated requirement.txt
